minor: task/module3-task1 add game screen component & simple functionality
htmlacademy-react/573447-guess-melody-5 pull request #4
Opened 2020-10-08 19:18 UTC by What1s1ove

2020-10-09 10:59 UTC, DmitryMarkov requested changes
В целом задание выполнено, есть небольшие замечания, которые стоит исправить (сброс ответов при переключении вопросов).

В целом похвально желание делать "профессионально", но лично мне не нравится создание десятков файлов, в каждом из которых один экспорт типа и функции. На проекте средней тяжести можно умереть от количества файлов в проекте.

Типы и интерфейсы можно не импортить вручную, если их поместить в файл `types.d.ts` в папке `src`. Они должны быть доступны во всех компонентах проекта

2020-10-09 10:59 UTC, DmitryMarkov commented on src/common/enums/game/genre-type.enum.ts
> +}
думаю, этот enum в будущем не понадобится, так как данные будут приходить с сервера и их придется поддерживать вручную, что приведет к рассинхронизации

2020-10-09 10:59 UTC, DmitryMarkov commented on src/common/interfaces/game/genre-question-answer.interface.ts
> +  genre: GenreType;
это всё будет работать только локально и на моках. мы не можем иметь контракт сервером в нашем проекте

2020-10-09 10:59 UTC, DmitryMarkov commented on src/components/app/app.tsx
> +        <GameScree questions={questions} />
```suggestion
        <GameScreen questions={questions} />
```

2020-10-09 10:59 UTC, DmitryMarkov commented on src/components/artist-question-answer/artist-question-answer.tsx
> +          id={answerLabel}
не вижу профита от использования useMemo здесь. Можешь обосновать?

2020-10-09 10:59 UTC, DmitryMarkov commented on src/components/artist-question-screen/artist-question-screen.tsx
> +        <a className="game__back" href="#">
можно использовать `Link`

2020-10-09 10:59 UTC, DmitryMarkov commented on src/components/game-screen/game-screen.tsx
> +  if (step >= questions.length || !currentQuestion) {
мы должны допускать не больше трех ошибок. Пока у нас нет проверки на ошибки, но сейчас мы проходим по всем вопросам

2020-10-09 10:59 UTC, DmitryMarkov commented on src/components/genre-question-screen/genre-question-screen.tsx
> +          <div className="wrong" />
Часть шаблона дублируется между экранов ответа на исполнителя и жанра. При этом к ним совершенно не относится. Её лучше вынести в отдельный компонент (или же сами вопросы ответы вынести), иначе потом будут проблемы

2020-10-09 10:59 UTC, DmitryMarkov commented on src/components/genre-question-screen/genre-question-screen.tsx
> +  const [answers, setAnswers] = React.useState<boolean[]>(DEFAULT_ANSWERS);
Сейчас ответы между разными вопросами запоминаются, так не должно быть. При смене скрина надо сбрасывать ответы

2020-10-09 10:59 UTC, DmitryMarkov commented on src/helpers/helpers.ts
> +export * from './mocks/mocks';
я бы не стал относить моки к хелперам (даже есть это хелперы моков). Пусть лежат и уйдут вместе

2020-10-09 18:26 UTC, ZubkoWhatislove commented on src/common/enums/game/genre-type.enum.ts
> +}
Согласен, исправлю

2020-10-09 18:27 UTC, What1s1ove commented on src/common/enums/game/genre-type.enum.ts
> +}
Согласен, исправлю

2020-10-09 18:30 UTC, What1s1ove commented on src/components/artist-question-answer/artist-question-answer.tsx
> +          id={answerLabel}
Недавно я увидел проект, где каждая функция и константа в компоненте реакт была обернуты с соответствующий хук. Мне понравилась задумка, и я хотел ты попробовать так же. Хоть где-то)

2020-10-09 18:31 UTC, What1s1ove commented on src/components/artist-question-screen/artist-question-screen.tsx
> +        <a className="game__back" href="#">
Да, конечно. Там еще есть места, где просто ссылки. Я стараюсь что бы проект был +- соответствовал проекту на лекциях. Я хотел это изменить, когда бы "пришло" время )

2020-10-09 18:32 UTC, What1s1ove commented on src/components/game-screen/game-screen.tsx
> +  if (step >= questions.length || !currentQuestion) {
Да у нас и нету функционала записи очков игры. Вроде это ещё рано реализовывать )

2020-10-09 18:34 UTC, What1s1ove commented on src/components/genre-question-screen/genre-question-screen.tsx
> +          <div className="wrong" />
Конечно у меня чешутся руки вынести повторяющиеся код. Но как я писал выше, я хотел бы проекты были похожи +- с учебным проектом на лекции

2020-10-09 18:36 UTC, What1s1ove commented on src/components/genre-question-screen/genre-question-screen.tsx
> +  const [answers, setAnswers] = React.useState<boolean[]>(DEFAULT_ANSWERS);
Да, я заметил этот баг(фичу). Но решил пока не исправлять, тк в проекте на лекциях он тоже есть )
Мне кажется он будет до того момента, пока не появится редакс )

Пс. исправлю

2020-10-09 18:41 UTC, What1s1ove commented on src/common/enums/game/genre-type.enum.ts
> +}
На большое сообщение в начале поста:

А мне нравится кстати что каждый файл лежит отдельно. Но больше чем это, мне нравится когда люди, у которых больше опыта, говорят как они хотели бы видеть это)
Исправлю, спасибо)

Пс, по-поводу функций-хелперов в отдельном файле. Обычно возле каждого такого хелпера, лежит тест для него. Но как оказалось, на интенсиве хелперы тестировать не нужно, по-этому уберу в один)

2020-10-10 08:28 UTC, DmitryMarkov commented on src/common/enums/game/genre-type.enum.ts
> +}
На интенсиве, может, и не нужно, а по жизни... почему нет? :)

2020-10-10 08:38 UTC, What1s1ove commented on src/common/enums/game/genre-type.enum.ts
> +}
По-жизни конечно. Но это все время... ☹️
Я сейчас большую часть трачу на описание типов/моков чем на саму таску :D 
Когда же это всё окупится )

2020-10-10 09:50 UTC, DmitryMarkov approved these changes
Отличная работа! 👍

2020-10-10 09:50 UTC, merged