patch: task/module7-task2 add api enum
htmlacademy-react/573447-guess-melody-5 pull request #9
Opened 2020-11-02 06:12 UTC by What1s1ove

2020-11-02 06:13 UTC, What1s1ove reviewed
Блин, почти все с заданий сделал в предыдущем задании ☹️
А без этого задания не открывает следующие

2020-11-02 19:37 UTC, DmitryMarkov requested changes
Код я посмотрел в предыдущем PR, вопросов нет. А вот по логике работы есть.

Если сразу зайти на страницу `http://localhost:1337/game` то перекидывает на логин, хотя в задании такого нет:

> Реализуйте логику показа экрана авторизации. Он должен рендериться, если пользователь победил, но при этом не авторизован.

При этом после авторизации я вижу экран победы с 0 отвеченных вопросов

2020-11-02 19:37 UTC, DmitryMarkov commented on src/components/private-route/__snapshots__/private-route.test.tsx.snap
> +exports[`PrivateRoute component should render PrivateRoute component 1`] = `null`;
ну, такое. Должен же проверять, чтобы на выходе было `<p>Private Component</p>`?

2020-11-04 17:44 UTC, What1s1ove commented
Разрезолвил замечание с роутом на `/game`. Иногда не сразу воспроизводит песню в хроме(ошибка с автоплеем)

2020-11-04 20:11 UTC, DmitryMarkov approved these changes

2020-11-04 20:11 UTC, merged